# SPDX-FileCopyrightText: 2021 Tobias Fella <fella@posteo.de>
# SPDX-License-Identifier: BSD-2-Clause

Dependencies:

- 'on': ['Linux/Qt', 'FreeBSD/Qt', 'Android/Qt']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kunitconversion': '@latest-kf6'
    'third-party/libqalculate': '@latest'

- 'on': ['Linux/Qt', 'FreeBSD/Qt']
  'require':
    'frameworks/qqc2-desktop-style': '@latest-kf6'

Options:
  cppcheck-arguments: '--enable=warning,style,performance --inline-suppr --suppress=passedByValue --suppress=nullPointer'
