# SPDX-FileCopyrightText: 2021 Tobias Fella <fella@posteo.de>
# SPDX-License-Identifier: BSD-2-Clause

Dependencies:

- 'on': ['Linux', 'FreeBSD', 'Android']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kunitconversion': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'
    'third-party/libqalculate': '@latest'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'

Options:
  cppcheck-arguments: '--enable=warning,style,performance --inline-suppr --suppress=passedByValue --suppress=nullPointer'
  require-passing-tests-on: [ 'Linux', 'Android', 'FreeBSD' ]